### ISSUE TITLE
有两个问题想请教

### ISSUE THREAD

**Issue by blood0708** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#1]
1. 
<object>
        <name>missing_hole</name>
        <pose>Unspecified</pose>
        <truncated>0</truncated>
        <difficult>0</difficult>
        <bndbox>
            <xmin>240</xmin>
            <ymin>404</ymin>
            <xmax>282</xmax>
            <ymax>437</ymax>
        </bndbox>
    </object>

数据标签的xml里面 xmin,ymin,xmax,ymax。是代表图像中的位置吗？两个点确定的矩形？

2. 我看您的数据是一块特定的PCB板子，如果我换一块板子，模型还能准确的找到缺陷吗？是不是每检测一块板子，都要构造这一块板子的数据集进行训练之后的模型才能使用？普通的物体识别的话，应该是不需要的。

**Comment by blood0708** [comment]
期待您的解答，谢谢

**Comment by Ixiaohuihuihui** [comment]
@blood0708 bounding box的框是由左上角的x和y坐标以及右下角的x和y坐标确定的。
换一块板子也能找到缺陷。例如，下面这个是我没有训练过的板子。
但换块板子，瑕疵要和训练过的瑕疵类似。
![s14](https://user-images.githubusercontent.com/26215859/59183465-a58bb180-8b9e-11e9-8b9a-1e92ab520f82.jpg)

**Comment by blood0708** [comment]
感谢您的解答
