### ISSUE TITLE
model not work

### ISSUE THREAD

**Issue by tienhoang1094** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#10]
hi, i run the code as u did but it have no detection in my result,any help ...
![image](https://user-images.githubusercontent.com/58082063/69944974-265ab300-151b-11ea-9be0-ecdf01a1bfa0.png)

**Comment by tienhoang1094** [comment]
![image](https://user-images.githubusercontent.com/58082063/69948075-8e13fc80-1521-11ea-9b32-f98786a48ca8.png)


python inference.py --data_dir='demos_backup' --save_dir='results'

**Comment by tienhoang1094** [comment]
when i drop threshold to 0.2 (above 0.6)
![image](https://user-images.githubusercontent.com/58082063/69950320-d1706a00-1525-11ea-8c66-4edda56b82bf.png)

**Comment by tienhoang1094** [comment]
i have solved this problem by changing code, but i still need ur answer .

**Comment by Ixiaohuihuihui** [comment]
Hi, I'm sorry for the late reply, I will set the automatic reminder open when someone open issues. 
![image](https://user-images.githubusercontent.com/26215859/70109183-11e6f980-1686-11ea-804e-cc5a0feccb90.png)
Did you change the checkpoint paths? If not, the model will be changed to pretrain model. 
And you will get nothing when detecting the defects.

**Comment by tienhoang1094** [comment]
ok tks bro, may i ask some private Q about TDD for my PCB dataset, cuz i think it much harder  than ur dataset

**Comment by Ixiaohuihuihui** [comment]
Of course, you can ask anything if I know

**Comment by tienhoang1094** [comment]
i have sent u an email, tks u so much!
