### ISSUE TITLE
Request for 图和

### ISSUE THREAD

**Issue by zhiwenxiaxia** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#13]

**Comment by zhiwenxiaxia** [comment]
this is a interesting work. I am tring to run your code, but the dataset link does not exist.
 would you please provide an available dataset link or send me one (my email: xianzw2011@163.com). Thanks in advance.

**Comment by Ixiaohuihuihui** [comment]
Sorry for the late reply, I will send you the dataset link in email.

**Comment by zhiwenxiaxia** [comment]
Thanks a lot
