### ISSUE TITLE
parameter

### ISSUE THREAD

**Issue by tienhoang1094** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#16]
Hi bro, if i want to detect defect much as possible in a pcb even defect with lowest prob, what  parameter in config i should change to make model more sensibility with defect ? ( even it detect wrong, as long as it don't miss any defect) 
i just khow to change threshold prob and IOU prob, anything else in config file ?

**Comment by Ixiaohuihuihui** [comment]
Oh, I didn't have a try on this problem, but I think that changing the threshold prob and IOU prob may be can help you.
