### ISSUE TITLE
Ask some dataset question

### ISSUE THREAD

**Issue by nctuaimmlabmember** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#17]
Dataset Update
The paper of this project will be update. However, the defect images of raw dataset are high-resolution. With the respect of such small dataset, data augmentation techniques are adopted before data training. The images are then cropped into 600 × 600 sub-images, forming our training set and testing set with 9920 and 2508 images, respectively.
Some instructions:
1、This augmented dataset is privately owned, if you want to use it in your paper, please contact me.

我想請問照上面的內容，作者您是否有更多相關擴充的PCB data，想和您索取這些內容，麻煩作者您的協助了，需要這些dataset來做相關的研究
@Ixiaohuihuihui

**Comment by Ixiaohuihuihui** [comment]
把你的邮箱地址发给我一下~我发给你

**Comment by nctuaimmlabmember** [comment]
感恩 我的郵箱地址如下 多一個備用的
qq851211.ee08g@nctu.edu.tw
setsuma52000@gmail.com

**Comment by Ixiaohuihuihui** [comment]
不客气，请查收，如果收到，我将关闭这个issue

**Comment by nctuaimmlabmember** [comment]
已收到 謝謝你

**Comment by Ixiaohuihuihui** [comment]
没事儿，哈哈
