### ISSUE TITLE
Use your dataset

### ISSUE THREAD

**Issue by josepl16** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#18]
Hello
I wanted to know if I could use your defective PCB database to test my Master End Job (TFM). I am implementing a flaw detector and I would like to test it with your dataset of images, only for academic use.

**Comment by Ixiaohuihuihui** [comment]
I'm sorrry for the late reply. Could you let me know your email? I'll send you.

**Comment by josepl16** [comment]
this is my mail: kidsain@gmail.com 
a lot of thanks

**Comment by Ixiaohuihuihui** [comment]
Hi, you can check your email. And if you don't have other questions, you can close this issue.
