### ISSUE TITLE
Not able to detect the images

### ISSUE THREAD

**Issue by git-abhijit** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#19]
Hi , 
Greetings. 
I was trying your project and followed the steps to run the inference.py to detect the fault pcb images, but it is not working for me. Would need your guidance to make it work. Thanks.

Development Environment
1. Python Version - 2.7.17
2. CUDA Version 8.0.44 , CUDNN=5.1.10 --> __This part I have not installed, as I am not running on GPU supported environment and my laptop doesn't support Nvida graphics card. I think this step can be avoided for execution of inference.py. Please comment on this observation.__
3. opencv installed
4. tfplot installed.
5. tensorflow == 1.12 installed.

**Configurations and Model Files**

ROOT_PATH = /home/root1/EALT/usecase/pcb/Tiny-Defect-Detection-for-PCB/

Downloaded  resnet50_v1、resnet101_v1 pre-trained models and placed in the below path

**/home/root1/EALT/usecase/pcb/Tiny-Defect-Detection-for-PCB/data/pretrained_weights**

![image](https://user-images.githubusercontent.com/48888213/88704472-bcd38880-d12b-11ea-8b7e-284c94d48ce1.png)

**Compilation** 
cd $PATH_ROOT/libs/box_utils/cython_utils
**python setup.py build_ext --inplace**

![image](https://user-images.githubusercontent.com/48888213/88704793-3cf9ee00-d12c-11ea-8934-60b3de37af75.png)
![image](https://user-images.githubusercontent.com/48888213/88704820-48e5b000-d12c-11ea-84fb-ad4fcdea745e.png)

Downloaded the trained weights from google drive and placed into the below path

![image](https://user-images.githubusercontent.com/48888213/88705037-995d0d80-d12c-11ea-9831-a9f38fe80b28.png)

**Content of Checkpoint file:-**
![image](https://user-images.githubusercontent.com/48888213/88705095-ae39a100-d12c-11ea-9330-72e32ea817c2.png)

Executed inference.py file 

**Console Log:-** 
~/EALT/usecase/pcb/Tiny-Defect-Detection-for-PCB/tools$ **python inference.py --data_dir='demos' --save_dir='results' --GPU='0'**
++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--
Weights Name ----------> resnet_v1_101
Called with args:
Namespace(GPU='0', data_dir='demos', save_dir='results')
.
.
.
.
.
var_in_graph:  resnet_v1_101/block3/unit_21/bottleneck_v1/conv2/BatchNorm/beta:0
var_in_ckpt:  resnet_v1_101/block3/unit_21/bottleneck_v1/conv2/BatchNorm/beta
____________________________________________________________
var_in_graph:  resnet_v1_101/block2/unit_2/bottleneck_v1/conv2/BatchNorm/moving_variance:0
var_in_ckpt:  resnet_v1_101/block2/unit_2/bottleneck_v1/conv2/BatchNorm/moving_variance
____________________________________________________________
var_in_graph:  resnet_v1_101/block3/unit_12/bottleneck_v1/conv3/weights:0
var_in_ckpt:  resnet_v1_101/block3/unit_12/bottleneck_v1/conv3/weights
____________________________________________________________
var_in_graph:  resnet_v1_101/block3/unit_22/bottleneck_v1/conv1/BatchNorm/moving_mean:0
var_in_ckpt:  resnet_v1_101/block3/unit_22/bottleneck_v1/conv1/BatchNorm/moving_mean
____________________________________________________________
var_in_graph:  resnet_v1_101/block3/unit_11/bottleneck_v1/conv3/BatchNorm/moving_mean:0
var_in_ckpt:  resnet_v1_101/block3/unit_11/bottleneck_v1/conv3/BatchNorm/moving_mean

restore from pretrained_weighs in IMAGE_NET
2020-07-29 00:03:16.358485: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
restore model

05.jpg
demos/05.jpg image cost 5.89661192894s:[>>>                                     ]10%    1/11--------------m13.jpg
demos/m13.jpg image cost 4.42273283005s:[>>>>>>>                          ]19%   2/11---------02_missing_hole_02.jpg
demos/02_missing_hole_02.jpg image cost 5.09217810631s:[>>>>>    ]28%    3/11-------
01_mouse_bite_05.jpg
demos/01_mouse_bite_05.jpg image cost 7.57943320274s:[>>>>>>> ]37%      4/11---------01_missing_hole_01.jpg
demos/01_missing_hole_01.jpg image cost 7.18763399124s:[>>>>>>  ]46%    5/11-------------------------------
08.jpg
demos/08.jpg image cost 4.95201611519s:[>>>>>>>>>>>>>>>>>>>>>]55%    6/11-------------------------------
spurs (12).jpg
demos/spurs (12).jpg image cost 5.14101982117s:[>>>>>>>>>>>>>     ]64%    7/11-------------------------------
06.jpg
demos/06.jpg image cost 4.86512613297s:[>>>>>>>>>>>>>>>>>>>> ]73%    8/11-------------------------------
s14.jpg
demos/s14.jpg image cost 4.10952091217s:[>>>>>>>>>>>>>>>>>>> ]82%   9/11-------------------------------
07.jpg
demos/07.jpg image cost 5.74381709099s:[>>>>>>>>>>>>>>>>>>>>]91%    10/112020-07-29 00:04:18.220891: W tensorflow/core/framework/allocator.cc:122] Allocation of 138285056 exceeds 10% of system memory.
11_short_05.jpg
demos/11_short_05.jpg image cost 4.12220191956s:[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100%  11/11

**Observation**
The result folder is having all the file present in the source folder, and the images having the error are not marked too, please refer the below snapshots. 

![image](https://user-images.githubusercontent.com/48888213/88707233-99124180-d12f-11ea-8557-1896115bf98f.png)

Please help in resolving this issue. Thanks.

**Comment by git-abhijit** [comment]
hi, 
Created folder FPN_Res101_0117_OHEM in output/trained_weights. 
In code checkpoint path is 
 checkpoint_path = tf.train.latest_checkpoint(os.path.join(cfgs.TRAINED_CKPT, cfgs.VERSION)

Description :
cfgs.TRAINED_CKPT = rootpath + /output/trained_weights 
cfgs.VERSION = FPN_Res101_0117_OHEM

Modified the contents of the checkpoint file. 
![image](https://user-images.githubusercontent.com/48888213/88782642-702f9200-d1ab-11ea-96f0-97a373946de4.png)

Now the PCB faults are getting recognised. 


![image](https://user-images.githubusercontent.com/48888213/88787528-9d7f3e80-d1b1-11ea-8419-6ec67752c249.png)

Closing this issue.

**Comment by Prahitha** [comment]
Hi, I'm trying to run this on my CPU too. However, I get an error during compilation: `OSError: The CUDA home path could not be located`, any idea how to fix this? Any help is appreciated. Thanks!
