### ISSUE TITLE
缺孔缺陷数据问题

### ISSUE THREAD

**Issue by LiuXinyu12378** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#21]

**Comment by LiuXinyu12378** [comment]
Hello ,你好同学，我觉得缺孔数据的PS制作是有问题的，电路板的制作是先打孔，如果是制作完成缺孔的电路板，它的中心不应该是绿色的，而是有锡的平面，就是和正常有孔的颜色差不多，只不过是中心没有孔的状态

**Comment by Ixiaohuihuihui** [comment]
嗯嗯，你学过就懂一些...........谢谢你的建议，但我们当时也不是学电路的，特别是当时几乎找不到什么数据集，就自己弄了一个数据集，还是有些问题的，但如果你有真实的PCB瑕疵数据集，可以用这个方法去检测。
