### ISSUE TITLE
本质是加了fpn的faster-rcnn？

### ISSUE THREAD

**Issue by liuxufenfeiya** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#23]
大致看了下build_whole_network.py的代码，感觉就是换了resnet101的、加了fpn以及一些tricks的faster-rcnn？
所以是一个two-stage的有全连接层的目标检测咯？这样精度确实提高了，不过速度就很慢了
那么想问下现在目标检测发展这么快，是否考虑过对比下最新的yolov4,v5以及anchor free的模型效果呢？
最后感谢作者开源。

**Comment by Ixiaohuihuihui** [comment]
你说得对....反正当时做的时候刚接触深度学习...啥也不懂 
之后我就没再做这个啦，所以就没有和最新的目标检测模型比较咯
