### ISSUE TITLE
No module named cython_bbox

### ISSUE THREAD

**Issue by Chaohao-Zhang** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#27]
我执行那个inference.py时候，他报错，错误提醒是：No module named cython_bbox。请问这个库或者文件在哪里呢。我也已经执行那个编译的“setup.py”

**Comment by Ixiaohuihuihui** [comment]
执行这个了吗？

cd $PATH_ROOT/libs/box_utils/cython_utils
python setup.py build_ext --inplace

**Comment by Ixiaohuihuihui** [comment]
Please refer #5

**Comment by Chaohao-Zhang** [comment]
谢谢你的答复。问题解决了
