### ISSUE TITLE
请问，你是用多大内存的GPU跑的？

### ISSUE THREAD

**Issue by HUI11126** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#28]
我用RTX 2060 6G不太够用，即使跑一张40*40的图片也不行。我见2017年的FPN paper上面写的是使用8个GPU

**Comment by Ixiaohuihuihui** [comment]
不用那么大，我当年用的是1张8G的1080...应该需要7G的内存

**Comment by HUI11126** [comment]
谢谢回复。我找到原因了，我把这两个参数设置得太大了。
IMG_SHORT_SIDE_LEN = 2048
IMG_MAX_LENGTH = 3072
