### ISSUE TITLE
The shared weights file not consistent with the master code

### ISSUE THREAD

**Issue by llhuii** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#3]
When restoring from the trained weights in https://pan.baidu.com/s/1rvHjihG1fL499SqU28Nang (i.e. `FPN_Res101_20181204/pcb_30000model.ckpt.data-00000-of-00001`), the exception below raised:
```python
InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1,1,512,6] rhs shape= [1,1,512,24]
         [[node save/Assign_25 (defined at ../libs/networks/build_whole_network.py:544)  = Assign[T=DT_FLOAT, _class=["loc:@build_rpn/rpn_cls_score/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](build_rpn/rpn_cls_score/weights, save/RestoreV2:25)]]

```		

Then I manually changed the line 29 of build_whole_network.py into ```self.num_anchors_per_location = len(cfgs.ANCHOR_SCALES) * len(cfgs.ANCHOR_RATIOS) * 4```, the weights could be restored, but another exception raised in postprocess_FPN.

So It seems the shared weights file is not consistent with the code.
@Ixiaohuihuihui could you share the weights matching the code?

**Comment by llhuii** [comment]
FYI, using the graph in trained weights i.e. `FPN_Res101_20181204/pcb_30000model.ckpt.meta`, it's no problem to restore from the weights.

**Comment by Ixiaohuihuihui** [comment]
Hi, llhuii!
The weights should be in the same folder,  for example, the trained weights folder contains: 
![image](https://user-images.githubusercontent.com/26215859/62675584-2bc74700-b9da-11e9-945b-0c81e477ca09.png)
And you don't need to specify a single file.

**Comment by llhuii** [comment]
Thank your reply.
Yes, they are in the same folder, and I use the config file `libs/configs/cfgs_res101_fpn.py`, so I rename `FPN_Res101_0117_OHEM` to `FPN_Res101_20181204`.
Can you help to check the md5sum of these files or restore them from the master code? Thank in advance.
![image](https://user-images.githubusercontent.com/419660/62680600-2d007000-b9ea-11e9-92ac-f0f4e76d93ac.png)

**Comment by llhuii** [comment]
There is the more information:
This rpn_cls_score conv2d has 3 * 2 output_channels in the master code definition, but has 24 output_channels  in trained weights (see the meta file pcb_30000model.ckpt.meta).
And the rpn_box_pred conv2d has the same issue.
the definition code:
![image](https://user-images.githubusercontent.com/419660/62681378-27a42500-b9ec-11e9-8c24-9fe1d1679e1a.png)

**Comment by Ixiaohuihuihui** [comment]
I'm sorry for my late reply!
I wonder that if you use **libs/configs/cfg.py**, can this code run successfully?
I can run this code without error, and other people also can get the same demo result. 
If you still can't run this code. please feel free to contact me!

**Comment by llhuii** [comment]
Hi, look that the original cfgs.py code, it indeed matches the number of out_channels(i.e. 24 for rpn_cls_score), I will try it.
PS: It seems that [the doc of the section demo](https://github.com/Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#demoavailable) is misleading.

[updated] ok now, thanks.

**Comment by Ixiaohuihuihui** [comment]
OK, thanks! I have changed it!
