### ISSUE TITLE
Question: what are the input / output names.

### ISSUE THREAD

**Issue by paulgavrikov** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#31]
Thanks for sharing this project! I am trying to convert this model to onnx but cannot find out the names of the input / outputs.
I believe the outputs are `postprocess_fastrcnn/concat:0,postprocess_fastrcnn/concat_1:0,postprocess_fastrcnn/concat_2:0` but am not sure about the inputs. Could you help?

**Comment by Ixiaohuihuihui** [comment]
Sorry, I don't know how to find this🤣🤣🤣
