### ISSUE TITLE
如何制作数据集？

### ISSUE THREAD

**Issue by hugh-98** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#33]
您好，我想问下您是如何PS出大量带有瑕疵的电路板图片的呢？我想在您给的数据集的基础上再加一些瑕疵，比如 焊点拉丝，请问应该如何进行批量图像处理？真心求问，期待您 的回答！

**Comment by Ixiaohuihuihui** [comment]
学一下PS？？
