### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by Prahitha** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#35]
When trying to compile using `python setup.py build_ext --inplace` I get an error that CUDA nvcc path could not be located. I've also tried to run inference.py and it says `no module named cython_bbox `. I've tried switching to Python 3.6 as mentioned in the earlier issue (#5) and that did not work for me. Is there a way to use this model without compiling it? Or maybe any idea why I might be getting this error? Thanks!

**Comment by Ixiaohuihuihui** [comment]
Sorry for the late reply.  I'm not sure about your environment. But I think it's a problem about wrong settings of environment. 😂
 Please refer to the related issues in https://github.com/DetectionTeamUCAS/FPN_Tensorflow/issues/80

**Comment by Prahitha** [comment]
Thanks for your reply. Can we not run it only on CPU though?

**Comment by Ixiaohuihuihui** [comment]
I think it can't run on CPU only😢

**Comment by Ixiaohuihuihui** [comment]
Have you solved this problem?

**Comment by Prahitha** [comment]
Yes, I was able to run it on Colab, thanks!
Reference: https://stackoverflow.com/questions/61475248/how-can-i-use-python-2-on-google-colab#

**Comment by JiaLim98** [comment]
Hi @Prahitha, can you share the colab file you created for this repo? It would be of great help! Thanks.

**Comment by Prahitha** [comment]
Hi @JiaLim98, here's the [link](https://colab.research.google.com/drive/13LehVMWeS2zm6vMQsu5lLLorvA1AECgH?usp=sharing). Hope this helps! Let me know if you still have trouble.
