### ISSUE TITLE
在windows 10上可以运行吗

### ISSUE THREAD

**Issue by Candy-1024** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#36]

**Comment by Ixiaohuihuihui** [comment]
你可以试一下。

**Comment by ShangGL123** [comment]
我用voc格式读取您的数据集时发现很多xml文件的filename和图片名对不上，xml中的name很多以256结尾的
![QQ截图20210422154520](https://user-images.githubusercontent.com/50814697/115676200-f0bda080-a381-11eb-8798-6ba8ecb99ef8.jpg)

**Comment by qinxin2583769975** [comment]
win10上跑出来了吗
