### ISSUE TITLE
Issue regarding opening and running the project.

### ISSUE THREAD

**Issue by vedantpathak** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#38]
Hey, I have downloaded the zip file and I'm confused how to run the project, can you please share steps as in which code should be executed first and after that which code?? That would be a huge help if you could provide a step by step process to execute and run the code/ project successfully,
Thank you in Advance.

**Comment by Ixiaohuihuihui** [comment]
Please follow the readme, it contains the steps.
