### ISSUE TITLE
How to create a labeled xml file from an image file?

### ISSUE THREAD

**Issue by admin0319** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#4]
Hi.

I'm testing it through your code.
I want to Train from my PCB image.
The linked PCB image contains an xml file.
How to create a labeled xml file from an image file?
please answer about my question.

Thank you.

**Comment by Ixiaohuihuihui** [comment]
Hi,
If you want to train your own data, you need to follow this instructions in [https://github.com/DetectionTeamUCAS/FPN_Tensorflow](url). In the section train, you need to re-make tfrecord.
Hope this be helpful for you!

**Comment by admin0319** [comment]
Thank you for quick response. I needed Annotation xml in Train of the link you told me, and I was curious how to make Annotation xml file from my image. After searching, I think you can use a tool like https://github.com/tzutalin/labelImg. Is there a better tool?

**Comment by Ixiaohuihuihui** [comment]
@admin0319 Yes, we labeled the images by the labelImg tool. The XML format should be consistent with VOC format. http://host.robots.ox.ac.uk/pascal/VOC/

**Comment by admin0319** [comment]
Thank you for your kind explanation!
It was a great help for my project. 
Thank you so much!
