### ISSUE TITLE
数据增强处理

### ISSUE THREAD

**Issue by qumj** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#41]
你好，请问数据增强是怎么处理的呢，有具体代码吗？ 使用图像增强的数据进行预测，预测结果如何拼接成原图呢。

**Comment by Ixiaohuihuihui** [comment]
不好意思，存放代码的旧服务器出了点问题，数据都被格式化了。但是你说的这个步骤网上已经有很多博客讲解了，就是分割图片时记住相对位置（offset）就可以啦
