### ISSUE TITLE
Number of Dataset

### ISSUE THREAD

**Issue by fityanul** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#46]
Dear @Ixiaohuihuihui,

In the explanation of the dataset, the number of images for training data and testing data is 9920 and 2508 images, these bring the total number of images: 12428. On the other hand, the annotated images provided in this Github are 10668 images or less than the total number of images used in Your experiments. Please help to give the explanation of this different number, since I need to use Your dataset for the research.

Thank You very much for Your help.

Warm Regards,
Fitya

**Comment by Ixiaohuihuihui** [comment]
Please refer to the quantity in my paper

**Comment by fityanul** [comment]
> Please refer to the quantity in my paper

Dear @Ixiaohuihuihui 

Thank You very much for the feedback

Warm Regards,
Fitya
