### ISSUE TITLE
Tensorflow install

### ISSUE THREAD

**Issue by imdone2** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#49]
Hello, when i do the 'pip install -r requirements.txt' i get this message:
"Collecting opencv-python
  Using cached opencv_python-4.5.5.64-cp36-abi3-win_amd64.whl (35.4 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.1 (from versions: 2.8.0rc1, 2.8.0, 2.9.0rc0, 2.9.0rc1)
ERROR: No matching distribution found for tensorflow==2.5.1"

Any idea on what i can do to bypass this?

**Comment by QixingJiang** [comment]
I think you shouldn't install the tensorflow in the requirement.txt
TF2 will cause some bugs. Some API changes result in incompatibility with this code.
TF1 is better, for me, I used tensorflow==1.15.0.
For the anthor, she used  1.12.1  .
May this answer help you anyway, good luck!
