### ISSUE TITLE
Cuda home

### ISSUE THREAD

**Issue by imdone2** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#51]
When I do 'python setup.py build_ext --inplace' I get this:
C:\LICENTA\Tiny-Defect-Detection-for-PCB-master\libs\box_utils\cython_utils>setup.py build_ext --inplace
Traceback (most recent call last):
  File "C:\LICENTA\Tiny-Defect-Detection-for-PCB-master\libs\box_utils\cython_utils\setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "C:\LICENTA\Tiny-Defect-Detection-for-PCB-master\libs\box_utils\cython_utils\setup.py", line 43, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

I tried setting cuda home in this folder, and all the previous ones, and tried to add them to path
![image](https://user-images.githubusercontent.com/104418086/166094940-9218153b-520f-4afc-b52c-3fb4192e2d9b.png)

and it doesn't seem to work, any ideas?
Thank you for your help

**Comment by Ixiaohuihuihui** [comment]
Hi, please check your cuda is OK. It seems you didn't install the correct GPU-cuda...............
