### ISSUE TITLE
Data Augmentation tool

### ISSUE THREAD

**Issue by 97irenet** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#57]
Hi, may I know what tool you used for data augmentation? and also data annotation?

**Comment by Ixiaohuihuihui** [comment]
等我投完论文，我一定整理一下哈~因为我之前放在旧服务器上的东西全都没有了，格式化了。。。所以我还得重新写一个。已经有太多人问我这个数据增强方法了，但其实网上有很多代码。我之后再整理下吧~8.20号之前🤣

**Comment by Ixiaohuihuihui** [comment]
https://github.com/liuguiyangnwpu/TinyObject/blob/c7c5e58fb3e345727051c426dc3ca127b83cd503/mainmodels/dataset/JLVideo/%E5%A4%A7%E5%9B%BE%E5%83%8F%E5%88%87%E5%88%86%E6%88%90%E5%B0%8F%E5%9B%BE%E5%83%8F.py


可以按照这个代码改
