### ISSUE TITLE
No module named 'libs.box_utils.cython_utils.cython_bbox'

### ISSUE THREAD

**Issue by gaoxumin** [Ixiaohuihuihui/Tiny-Defect-Detection-for-PCB#9]
您好，报错如上,libs.box_utils.cython_utils下面确实没有cython_bbox，您知道怎么做吗？

**Comment by Ixiaohuihuihui** [comment]
cd $PATH_ROOT/libs/box_utils/cython_utils
python setup.py build_ext --inplace

**Comment by Ixiaohuihuihui** [comment]
![image](https://user-images.githubusercontent.com/26215859/69788595-d073cb80-11f9-11ea-8413-39f96c0ba427.png)
